### PR TITLE
Update SVD.adoc

### PR DESCRIPTION
**Pull request by Ken-Iijima**
Correct some LaTeX syntax.

### CODE REVIEW

**Comment by zbynek** [comment]
Thanks, any reason for having 2 matrices right-aligned and one centered?

**Comment by Ken-Iijima** [comment]
I compared right-aligned, left-aligned, and centered options, and this one looked the most natural. Do you think it would be better if all three were right-aligned?

**Comment by zbynek** [comment]
I think having them all right-aligned is the most consistent with the actual output in CAS.
image
Maybe let's use that in the documentation too? I don't have a strong preference.

**Comment by Ken-Iijima** [comment]
It seems that way in the CAS output. Let’s use {rr} in the document as well.
I think the LaTeX corrections are almost complete in the English version as well. Thank you.

**Pull request merged**
